---
listener: localhost:4711
logger:
  level: info
database:
  path: ./data
  workspace: pascal-1
pipeline:
- name: sources.file
  path: 'data/eventlog.csv'
  read-from: start
  connects:
  - name: transforms.csv_parser
    delimiter: ';'
    timestamp-column: 0
    case-id-column: 1
    activity-column: 2
    timestamp-format: '02/01/2006 15:04:05.000'
    timestamp-tz-iana-key: Europe/Berlin
    connects:
    - name: transforms.event_buffer
      max-events: 500000
      max-age: 30s
      flush-interval: 20s
      connects:
      - name: sinks.dfg
      - name: sinks.event