---
sources:
  - enabled: false
    file-config:
      path: '/Volumes/Pascals Drive/Argos Miner/TrackingDB_Part2.csv'
      read-from: start
    csv-parser:
      delimiter: ';'
      process-instance-column: 4
      activity-column: 12
      timestamp-column: 9
      timestamp-format: '02/01/2006 15:04:05.000000'
      timestamp-tz-iana-key: Europe/Berlin
      ignore-when:
        - column: 10
          condition: '!='
          value: gestartet
  - enabled: true
    kafka-config:
      brokers:
      - 'localhost:9092'
      group-id: kafka-reader-1
      topic: pmlogs
      min-bytes: 10e3 # 10KB
      max-bytes: 10e6 # 10MB
    json-parser:
      
