---
listener: localhost:4711
logger:
  level: info
db:
  path: /Volumes/PascalsSSD/ArgosMiner/badgerv2_nopointer_nosync
ignore-activities:
  - name: 'krankenAngeboteWiederherstellen::Start'
  - name: '.*::Start'
    remove: true
sources:
  - enabled: false
    file-config:
      path: 'data/eventlog.csv'
      read-from: start
    csv-parsers:
      - delimiter: ';'
        case-id-column: 4
        activity-column: 5
        timestamp-column: 9
        timestamp-format: '02/01/2006 15:04:05.000000'
        timestamp-tz-iana-key: Europe/Berlin
        ignore-when:
          - column: 10
            condition: '!='
            value: gestartet
  - enabled: true
    kafka-config:
      brokers: 'localhost:9092'
      group-id: consumer-group-4711-10006
      timeout: 5s
      commit-interval: 1s
      topic: pmlogs
      min-bytes: 10e3 # 10KB
      max-bytes: 10e6 # 10MB
    json-parsers:
      - json-path: my_event
        activity-path: activity
        case-id-path: process_instance_id
        timestamp-path: '@timestamp'
        timestamp-format: '2006-01-02T15:04:05.000-0700'
        timestamp-tz-iana-key: Europe/Berlin
  #- enabled: true
  #  file-config:
  #    path: '/Users/pascalbudner/Desktop/test.json'
  #    read-from: start
  #  json-parser:
  #    json-path: my_json
  #    activity-path: activity
  #    process-instance-path: process_instance_id
  #    timestamp-path: '@timestamp'
  #    timestamp-format: '2006-01-02T15:04:05.000-0700'
  #    timestamp-tz-iana-key: Europe/Berlin
