version: "3.8"

services:

  my_engine:
    build: 
      dockerfile: Dockerfile
      context: ./
    environment:
      PORT: 8080
    volumes:
      - /Volumes/Pascals Drive/Argos Miner/:/Volumes/Pascals Drive/Argos Miner/
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
    depends_on: 
      - influxdb
      - my_redis

  my_redis:
    image: redis:6.2
    ports:
      - 6379:6379

  influxdb:
    image: influxdb:2.0.7-alpine
    ports:
      - "8086:8086"
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
